###configfile


options:
   readgroup:
      platform: ILUMINA
      centre: CENTRE

####TRAD

	
	


references:

    species: homo_sapiens
    
    build: GRCh38
    
    chromosomes: [ "1", "2", "3", "4", "5", "6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "X", "Y"]
    
    
    TAPD:
        
        annotate: True
    
#################################################################################################################################################

    
rules:


    becftools:
        
        extra:[]
        threads:
        
        
        
     VEP:
        
        extra:[]
        threads:
        
        
     SNPeff:
        
        extra:[]
        threads:
   
   
     ANNOVAR:
        
        extra:[]
        threads:
        
        
        
     rdeep:
        
        extra:[]

##########################################################################################################################################################


    input:
    
    
    
###########################################################################################################################################################


#samples

#######################################################################################################################333


samples:

